name: epub_builder
version: 0.1.1
description: A simple epub3 file builder with a minimal set of input data (authors, title, chapter list) and additional optional parameters.
homepage: https://github.com/adkrix/epub_builder
repository: https://github.com/adkrix/epub_builder

environment:
  sdk: ^3.9.0

dependencies:
  archive: ^4.0.7
  path: ^1.9.1
  xml: ^6.6.1
  uuid: ^4.5.2

dev_dependencies:
  markdown: ^7.3.0
  yaml: ^3.1.3
  test: ^1.25.6
  lints: ^6.0.0
  http: ^1.6.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

topics:
  - epub
  - epub3
  - generator
  - builder
  - creator

